trigger:
  branches:
    include:
    - main
    - develop



variables:
  NODE_VERSION: '18.x'

stages:
- stage: Test
  displayName: 'Run Playwright Tests'
  jobs:
  - job: PlaywrightTests
    displayName: 'Execute Playwright Test Suite'
    steps:
    
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: $(NODE_VERSION)
    
    - script: |
        npm ci
      displayName: 'Install dependencies'
    
    - script: |
        npx playwright install --with-deps
      displayName: 'Install Playwright browsers'
    
    - script: |
        npx playwright test
      displayName: 'Run Playwright tests'
      continueOnError: true
    
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: always()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results/junit.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Playwright Test Results'
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Playwright report'
      condition: always()
      inputs:
        targetPath: 'playwright-report'
        artifact: 'playwright-report'
        publishLocation: 'pipeline'
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish test artifacts'
      condition: failed()
      inputs:
        targetPath: 'test-results'
        artifact: 'test-results'
        publishLocation: 'pipeline'